name: flutter_notation_example
description: ""

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter_music_notation:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Bravura
      fonts:
        - asset: assets/fonts/Bravura.otf
    - family: Petaluma
      fonts:
        - asset: assets/fonts/Petaluma.otf
